# Generated by Django 4.2 on 2023-04-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyedinn', '0002_cartorder_category_product_tags_wishlist_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
