# Generated by Django 4.2 on 2023-05-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyedinn', '0008_product_life_product_mfd_product_stock_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=30),
        ),
    ]
